In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
orders = pd.read_csv('../data/Orders.csv')
returns = pd.read_csv('../data/Returns.csv')

In [3]:
pd.set_option('display.max_columns', 24)

In [4]:
orders.sample(5)
orders.shape

(51290, 24)

In [5]:
returns.sample(5)
returns.shape

(1079, 3)

In [6]:
orders['Sales'] = [x.replace('$', '') for x in orders['Sales']]
orders['Sales'] = [x.replace(',', '') for x in orders['Sales']]
orders['Sales'].dtype

dtype('O')

In [7]:
orders['Sales'] = orders['Sales'].astype(float)
orders['Sales'].dtype

dtype('float64')

In [8]:
orders['Profit'] = [x.replace('$', '') for x in orders['Profit']]
orders['Profit'] = [x.replace(',', '') for x in orders['Profit']]

In [9]:
orders['Profit'] = orders['Profit'].astype(float)

In [10]:
orders['Profit'].dtype

dtype('float64')

In [11]:
orders.sample(10)

,Row.ID,Order.ID,Order.Date,Ship.Date,Ship.Mode,Customer.ID,Customer.Name,Segment,Postal.Code,City,State,Country,Region,Market,Product.ID,Category,Sub.Category,Product.Name,Sales,Quantity,Discount,Profit,Shipping.Cost,Order.Priority
278,879,MX-2015-TM2149031-42329,11/21/15,11/21/15,Same Day,TM-2149031,Tony Molinari,Consumer,NaN,Camagüey,Camagüey,Cuba,Caribbean,LATAM,TEC-CO-3597,Technology,Copiers,"Brother Fax Machine, High-Speed",1053.69,5,0.002,441.29,367.549,High
35920,9599,MX-2012-TZ2144551-41157,9/5/12,9/10/12,Standard Class,TZ-2144551,Tom Zandusky,Corporate,NaN,Villa Canales,Guatemala,Guatemala,Central America,LATAM,OFF-AR-3460,Office Supplies,Art,"BIC Pencil Sharpener, Blue",38.68,2,0.000,18.16,3.312,Medium
32562,39728,CA-2015-KN16450140-42317,11/9/15,11/14/15,Standard Class,KN-164501406,Kean Nguyen,Corporate,21215.0,Baltimore,Maryland,United States,Eastern US,USCA,FUR-FU-4764,Furniture,Furnishings,Howard Miller Distant Time Traveler Alarm Clock,274.20,10,0.000,112.42,22.890,High
31781,6988,MX-2014-RE1945036-41791,6/1/14,6/7/14,Standard Class,RE-1945036,Richard Eichhorn,Consumer,NaN,Santo Domingo,Santo Domingo,Dominican Republic,Caribbean,LATAM,FUR-FU-3957,Furniture,Furnishings,"Deflect-O Stacking Tray, Erganomic",29.76,4,0.500,-15.52,4.738,Low
12890,22925,IN-2015-BD1177027-42260,9/13/15,9/17/15,Second Class,BD-1177027,Bryan Davis,Consumer,NaN,Hangzhou,Zhejiang,China,Eastern Asia,Asia Pacific,FUR-FU-5736,Furniture,Furnishings,"Rubbermaid Photo Frame, Duo Pack",259.05,5,0.000,124.20,24.270,High
36382,49431,TU-2015-DV3045134-42335,11/27/15,12/1/15,Standard Class,DV-3045134,Darrin Van Huff,Corporate,NaN,Izmir,Izmir,Turkey,Western Asia,Asia Pacific,TEC-PH-3139,Technology,Phones,"Apple Office Telephone, Cordless",27.25,1,0.600,-6.83,3.180,High
11101,28587,IN-2014-CM1183027-41699,3/1/14,3/5/14,Standard Class,CM-1183027,Cari MacIntyre,Corporate,NaN,Sanming,Fujian,China,Eastern Asia,Asia Pacific,TEC-CO-6008,Technology,Copiers,"Sharp Personal Copier, Laser",360.00,3,0.000,133.20,29.140,Medium
30269,48206,HR-2013-BP129030-41618,12/10/13,12/17/13,Standard Class,BP-129030,Beth Paige,Consumer,NaN,Zagreb,Grad Zagreb,Croatia,Southern Europe,Europe,OFF-BI-3726,Office Supplies,Binders,"Cardinal Binding Machine, Economy",99.54,2,0.000,27.84,5.370,Medium
20530,48584,IZ-2015-EJ415561-42229,8/13/15,8/17/15,Standard Class,EJ-415561,Eva Jacobs,Consumer,NaN,Baghdad,Baghdad,Iraq,Western Asia,Asia Pacific,FUR-BO-5973,Furniture,Bookcases,"Sauder Stackable Bookrack, Traditional",146.28,1,0.000,21.93,11.940,Medium
38778,7452,MX-2014-VP2173082-41902,9/20/14,9/25/14,Standard Class,VP-2173082,Victor Preis,Home Office,NaN,Mexico City,Distrito Federal,Mexico,Central America,LATAM,OFF-AR-3495,Office Supplies,Art,"Binney & Smith Pens, Blue",23.88,3,0.000,1.38,2.533,Medium

In [12]:
orders.columns

Index(['Row.ID', 'Order.ID', 'Order.Date', 'Ship.Date', 'Ship.Mode',
       'Customer.ID', 'Customer.Name', 'Segment', 'Postal.Code', 'City',
       'State', 'Country', 'Region', 'Market', 'Product.ID', 'Category',
       'Sub.Category', 'Product.Name', 'Sales', 'Quantity', 'Discount',
       'Profit', 'Shipping.Cost', 'Order.Priority'],
      dtype='object')

In [13]:
orders['Order.Date'] = pd.to_datetime(orders['Order.Date'])

In [14]:
orders['Order.Date'].dtype

dtype('<M8[ns]')

In [15]:
orders['Ship.Date'] = pd.to_datetime(orders['Ship.Date'])

In [16]:
orders['Month'] = [x.month for x in orders['Order.Date']]
orders.sample(5)

,Row.ID,Order.ID,Order.Date,Ship.Date,Ship.Mode,Customer.ID,Customer.Name,Segment,Postal.Code,City,State,Country,...,Market,Product.ID,Category,Sub.Category,Product.Name,Sales,Quantity,Discount,Profit,Shipping.Cost,Order.Priority,Month
18141,9755,US-2014-DL1331555-42001,2014-12-28,2014-12-29,First Class,DL-1331555,Delfina Latchford,Consumer,NaN,Choloma,Cortés,Honduras,...,LATAM,OFF-FA-6184,Office Supplies,Fasteners,"Stockwell Clamps, 12 Pack",74.64,10,0.4,-33.76,14.753,Critical,12
3676,44351,IS-2014-AS13563-41923,2014-10-11,2014-10-15,Standard Class,AS-13563,Adrian Shami,Home Office,NaN,Ashdod,Southern,Israel,...,Asia Pacific,TEC-PH-5267,Technology,Phones,"Motorola Smart Phone, Cordless",1285.56,2,0.0,89.94,85.210,Medium,10
4376,32439,CA-2012-AP10915140-41180,2012-09-28,2012-10-02,Standard Class,AP-109151404,Arthur Prichep,Consumer,90045.0,Los Angeles,California,United States,...,USCA,OFF-FA-6192,Office Supplies,Fasteners,Stockwell Push Pins,8.72,4,0.0,2.88,1.290,High,9
46499,49774,TU-2015-BK1260134-42311,2015-11-03,2015-11-07,Second Class,BK-1260134,Berenike Kampe,Consumer,NaN,Ankara,Ankara,Turkey,...,Asia Pacific,OFF-FA-5469,Office Supplies,Fasteners,"OIC Paper Clips, Bulk Pack",5.77,1,0.6,-1.61,1.530,Medium,11
32274,660,US-2014-GK14620101-41744,2014-04-15,2014-04-20,Standard Class,GK-14620101,Grace Kelly,Corporate,NaN,Lima,Lima (city),Peru,...,LATAM,OFF-FA-3061,Office Supplies,Fasteners,"Advantus Rubber Bands, Assorted Sizes",44.93,8,0.4,-0.83,4.544,Medium,4

In [17]:
by_cat = orders.groupby(['Month', 'Category']).agg({'Quantity':sum}).reset_index()

by_cat
# furn = by_cat[by_cat['Category'] == 'Furniture']
# ofc = by_cat[by_cat['Category'] == 'Office Supplies']
# tech = by_cat[by_cat['Category'] == 'Technology']

# cats = [furn, ofc, tech]

# for i in cats:
#     i.plot.bar(x='Month', y='Quantity')

    Month         Category  Quantity
0       1        Furniture      1750
1       1  Office Supplies      5480
2       1       Technology      1642
3       2        Furniture      1494
4       2  Office Supplies      4340
5       2       Technology      1595
6       3        Furniture      2098
7       3  Office Supplies      6283
8       3       Technology      2009
9       4        Furniture      2005
10      4  Office Supplies      6391
11      4       Technology      2070
12      5        Furniture      2484
13      5  Office Supplies      8170
14      5       Technology      2542
15      6        Furniture      3434
16      6  Office Supplies     11012
17      6       Technology      3563
18      7        Furniture      2157
19      7  Office Supplies      6618
20      7       Technology      2271
21      8        Furniture      3059
22      8  Office Supplies     11019
23      8       Technology      3518
24      9        Furniture      4111
25      9  Office Supplies     12572
26      9       Technology      3796
27     10        Furniture      3323
28     10  Office Supplies      9585
29     10       Technology      3395
30     11        Furniture      4471
31     11  Office Supplies     13529
32     11       Technology      4379
33     12        Furniture      4506
34     12  Office Supplies     13245
35     12       Technology      4396

In [18]:
#losses = orders.loc[orders['Profit'] < 0]
#sum(round(losses['Profit'], 2))

returns.columns = ['Returned', 'Order.ID', 'Region']

In [19]:
returns.merge(orders, how='inner', left_on='Order.ID')

In [20]:
returns.sample(5)
returns.shape

(2220, 27)

In [21]:
returns['Year'] = [x.year for x in returns['Order.Date']]

In [22]:
#returns.groupby('Year').agg({'Profit': sum})

neg_profit = returns.loc[returns['Profit'] < 0]
neg_profit.groupby('Year').agg({'Profit': sum})

        Profit
Year
2012  -5772.54
2013  -7713.03
2014  -7439.43
2015 -15907.60

In [23]:
repeat_ret = returns.groupby('Customer.ID').agg({'Quantity': sum}).sort_values(by = 'Quantity', ascending=False)

more_than_one = len(repeat_ret.loc[repeat_ret['Quantity'] > 1])

more_than_five = len(repeat_ret.loc[repeat_ret['Quantity'] > 5])

repeat_ret

returns.loc[returns['Customer.ID'] == 'PO-1885082']

,Returned,Order.ID,Region_x,Row.ID,Order.Date,Ship.Date,Ship.Mode,Customer.ID,Customer.Name,Segment,Postal.Code,City,...,Product.ID,Category,Sub.Category,Product.Name,Sales,Quantity,Discount,Profit,Shipping.Cost,Order.Priority,Month,Year
712,Yes,MX-2015-PO1885082-42279,Central America,9952,2015-10-02,2015-10-07,Standard Class,PO-1885082,Patrick O'Brill,Consumer,NaN,Juárez,...,TEC-PH-3802,Technology,Phones,"Cisco Signal Booster, VoIP",405.12,4,0.0,52.64,45.090,Medium,10,2015
713,Yes,MX-2015-PO1885082-42279,Central America,9955,2015-10-02,2015-10-07,Standard Class,PO-1885082,Patrick O'Brill,Consumer,NaN,Juárez,...,FUR-CH-4700,Furniture,Chairs,"Hon Steel Folding Chair, Set of Two",267.74,6,0.2,20.06,32.089,Medium,10,2015
714,Yes,MX-2015-PO1885082-42279,Central America,9948,2015-10-02,2015-10-07,Standard Class,PO-1885082,Patrick O'Brill,Consumer,NaN,Juárez,...,TEC-AC-4165,Technology,Accessories,"Enermax Memory Card, Programmable",540.82,7,0.0,237.86,21.081,Medium,10,2015
715,Yes,MX-2015-PO1885082-42279,Central America,9956,2015-10-02,2015-10-07,Standard Class,PO-1885082,Patrick O'Brill,Consumer,NaN,Juárez,...,TEC-MA-6147,Technology,Machines,"StarTech Printer, Durable",341.72,2,0.0,136.68,16.591,Medium,10,2015
716,Yes,MX-2015-PO1885082-42279,Central America,9958,2015-10-02,2015-10-07,Standard Class,PO-1885082,Patrick O'Brill,Consumer,NaN,Juárez,...,TEC-MA-5012,Technology,Machines,"Konica Phone, White",169.20,3,0.0,25.38,12.310,Medium,10,2015
717,Yes,MX-2015-PO1885082-42279,Central America,9947,2015-10-02,2015-10-07,Standard Class,PO-1885082,Patrick O'Brill,Consumer,NaN,Juárez,...,OFF-EN-5032,Office Supplies,Envelopes,"Kraft Interoffice Envelope, with clear poly wi...",168.20,5,0.0,74.00,10.917,Medium,10,2015
718,Yes,MX-2015-PO1885082-42279,Central America,9954,2015-10-02,2015-10-07,Standard Class,PO-1885082,Patrick O'Brill,Consumer,NaN,Juárez,...,TEC-PH-5844,Technology,Phones,"Samsung Speaker Phone, Full Size",747.18,9,0.0,358.56,10.128,Medium,10,2015
719,Yes,MX-2015-PO1885082-42279,Central America,9951,2015-10-02,2015-10-07,Standard Class,PO-1885082,Patrick O'Brill,Consumer,NaN,Juárez,...,OFF-BI-4805,Office Supplies,Binders,"Ibico 3-Hole Punch, Economy",40.60,2,0.0,10.52,4.548,Medium,10,2015
720,Yes,MX-2015-PO1885082-42279,Central America,9946,2015-10-02,2015-10-07,Standard Class,PO-1885082,Patrick O'Brill,Consumer,NaN,Juárez,...,OFF-EN-3658,Office Supplies,Envelopes,"Cameo Clasp Envelope, Security-Tint",39.70,5,0.0,5.10,3.717,Medium,10,2015
721,Yes,MX-2015-PO1885082-42279,Central America,9953,2015-10-02,2015-10-07,Standard Class,PO-1885082,Patrick O'Brill,Consumer,NaN,Juárez,...,OFF-SU-6165,Office Supplies,Supplies,"Stiletto Letter Opener, Easy Grip",60.00,3,0.0,14.40,3.221,Medium,10,2015
722,Yes,MX-2015-PO1885082-42279,Central America,9950,2015-10-02,2015-10-07,Standard Class,PO-1885082,Patrick O'Brill,Consumer,NaN,Juárez,...,OFF-AR-3484,Office Supplies,Art,"Binney & Smith Highlighters, Water Color",13.18,1,0.0,1.30,2.004,Medium,10,2015
723,Yes,MX-2015-PO1885082-42279,Central America,9957,2015-10-02,2015-10-07,Standard Class,PO-1885082,Patrick O'Brill,Consumer,NaN,Juárez,...,OFF-EN-3110,Office Supplies,Envelopes,"Ames Peel and Seal, Set of 50",24.92,2,0.0,0.24,1.866,Medium,10,2015
724,Yes,MX-2015-PO1885082-42279,Central America,9949,2015-10-02,2015-10-07,Standard Class,PO-1885082,Patrick O'Brill,Consumer,NaN,Juárez,...,OFF-EN-4440,Office Supplies,Envelopes,"GlobeWeis Interoffice Envelope, Security-Tint",66.96,2,0.0,20.72,1.264,Medium,10,2015

In [24]:
returns.groupby('Region_x').agg({'Quantity': sum}).sort_values(by = 'Quantity', ascending=False)

                   Quantity
Region_x
Western Europe          940
Central America         885
Western US              674
Oceania                 565
Southeastern Asia       508
Eastern US              487
Eastern Asia            472
South America           465
Southern Europe         423
Southern US             346
Southern Asia           328
Central US              289
Northern Europe         272
Western Asia            263
Caribbean               253
North Africa            113
Western Africa          111
Eastern Europe           91
Southern Africa          62
Eastern Africa           37
Central Africa           33
Eastern Canada           27
Central Asia             25
Western Canada            6

In [25]:
returns.groupby('Category').agg({'Quantity': sum}).sort_values(by = 'Quantity', ascending=False)

                 Quantity
Category
Office Supplies      4605
Technology           1556
Furniture            1514

In [26]:
returns.groupby('Sub.Category').agg({'Quantity': sum}).sort_values(by = 'Quantity', ascending=False)

              Quantity
Sub.Category
Binders            912
Art                749
Storage            702
Paper              528
Phones             523
Chairs             506
Accessories        503
Furnishings        497
Labels             480
Bookcases          361
Supplies           351
Fasteners          347
Envelopes          336
Copiers            310
Machines           220
Appliances         200
Tables             150

#  Part 2

In [27]:
returns_bool = returns[['Returned', 'Order.ID']]
returns_bool

     Returned                  Order.ID
0         Yes  CA-2012-SA20830140-41210
1         Yes  IN-2012-PB19210127-41259
2         Yes  IN-2012-PB19210127-41259
3         Yes  IN-2012-PB19210127-41259
4         Yes  IN-2012-PB19210127-41259
5         Yes  IN-2012-PB19210127-41259
6         Yes  IN-2012-PB19210127-41259
7         Yes  IN-2012-PB19210127-41259
8         Yes  IN-2012-PB19210127-41259
9         Yes  CA-2012-SC20095140-41174
10        Yes  CA-2012-SC20095140-41174
11        Yes  CA-2012-SC20095140-41174
12        Yes  CA-2012-SC20095140-41174
13        Yes    IN-2015-JH158207-42140
14        Yes    IN-2015-JH158207-42140
15        Yes    IN-2015-JH158207-42140
16        Yes    IN-2015-JH158207-42140
17        Yes    IN-2014-LC168857-41747
18        Yes   ID-2013-AB1001527-41439
19        Yes   ID-2013-AB1001527-41439
20        Yes   ES-2015-RA1994545-42218
21        Yes  CA-2014-TB21280140-41724
22        Yes  ES-2014-JF15295120-41924
23        Yes   IN-2014-NM1844527-41800
24        Yes   IN-2014-NM1844527-41800
25        Yes   IN-2014-NM1844527-41800
26        Yes    IN-2015-GB145307-42260
27        Yes    ES-2012-SC208458-41070
28        Yes  TU-2013-SF10200134-41417
29        Yes  TU-2013-SF10200134-41417
...       ...                       ...
2190      Yes  CA-2015-SC20575140-42236
2191      Yes  CA-2015-GK14620140-42257
2192      Yes   ZA-2015-MN7935147-42339
2193      Yes   ES-2012-AA1064564-41268
2194      Yes    IN-2015-MO178007-42363
2195      Yes  CA-2013-AI10855140-41628
2196      Yes  ES-2015-WB21850139-42248
2197      Yes     AG-2014-CM21603-41755
2198      Yes    IN-2012-RC198257-41167
2199      Yes    IN-2013-JM152657-41576
2200      Yes   TU-2012-PF9165134-41074
2201      Yes  US-2012-TH21235140-41216
2202      Yes   US-2013-PF1916582-41445
2203      Yes  CA-2015-AA10645140-42314
2204      Yes  ES-2012-MO17950120-41137
2205      Yes   ES-2013-PB1915034-41373
2206      Yes    NI-2014-CG204095-41856
2207      Yes    NI-2015-EB411095-42174
2208      Yes  IN-2014-KD16345144-41768
2209      Yes  IN-2015-LA16780102-42095
2210      Yes   IN-2014-SE2011066-41772
2211      Yes   ES-2015-AS1024064-42297
2212      Yes   ZA-2014-LS6945147-41672
2213      Yes  TU-2014-SF10965134-41992
2214      Yes  US-2014-LB16795140-41957
2215      Yes   IN-2014-DA1345058-41769
2216      Yes  US-2013-HG14845140-41530
2217      Yes   US-2013-SJ2021582-41543
2218      Yes  CA-2015-EB13870140-42269
2219      Yes    EG-2014-PM894038-41846

[2220 rows x 2 columns]

In [28]:
orders = orders.merge(returns_bool, how='outer', on='Order.ID')

In [29]:
orders['Returned'] = [1 if x == 'Yes' else 0 for x in orders['Returned']]

In [30]:
orders['Process.Time'] = orders['Ship.Date'] - orders['Order.Date']

In [31]:
orders.sample(5)

,Row.ID,Order.ID,Order.Date,Ship.Date,Ship.Mode,Customer.ID,Customer.Name,Segment,Postal.Code,City,State,Country,...,Category,Sub.Category,Product.Name,Sales,Quantity,Discount,Profit,Shipping.Cost,Order.Priority,Month,Returned,Process.Time
5088,50190,CG-2014-JK562533-41949,2014-11-06,2014-11-11,Standard Class,JK-562533,Jim Karlsson,Consumer,NaN,Kinshasa,Kinshasa,Democratic Republic of the Congo,...,Technology,Accessories,"Memorex Mouse, Bluetooth",112.68,4,0.0,4.44,9.16,Medium,11,0,5 days
15643,19810,ES-2014-DJ1342048-41980,2014-12-07,2014-12-08,First Class,DJ-1342048,Denny Joy,Corporate,NaN,Halle,North Rhine-Westphalia,Germany,...,Office Supplies,Binders,"Wilson Jones Binding Machine, Durable",151.38,3,0.0,2.97,6.10,Medium,12,0,1 days
46398,19179,ES-2012-SB2018548-41065,2012-06-05,2012-06-07,Second Class,SB-2018548,Sarah Brown,Consumer,NaN,Cologne,North Rhine-Westphalia,Germany,...,Office Supplies,Labels,"Avery Color Coded Labels, 5000 Label Set",13.68,1,0.0,4.77,3.65,Critical,6,0,2 days
14489,43783,UP-2013-AJ795137-41591,2013-11-13,2013-11-16,Second Class,AJ-795137,Anthony Johnson,Corporate,NaN,Kharkiv,Kharkiv,Ukraine,...,Technology,Machines,"Konica Receipt Printer, Wireless",489.00,4,0.0,97.80,54.29,Medium,11,0,3 days
48857,44428,TU-2013-IM5070134-41440,2013-06-15,2013-06-19,Standard Class,IM-5070134,Irene Maddox,Consumer,NaN,Bursa,Bursa,Turkey,...,Office Supplies,Binders,"Wilson Jones Binder Covers, Economy",4.48,1,0.6,-3.83,1.36,Medium,6,0,4 days